#配置数据库信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.8.128:3306/vueblog?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    #    url: jdbc:mysql://192.168.191.159:3306/authority_management?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    #    password: root
    initial-size: 20
    max-active: 50
    min-idle: 30
  #配置redis
  redis:
    host: 192.168.191.159
    port: 6379
    password:
    database:  0
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 300000ms

#指定mybatisPlus扫描的xml文件
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#指定端口
server:
  port: 8081

#jwt加密
gyg:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: authorization

