spring:
  profiles:
    active: dev
  mail:
    host: smtp.qq.com #发件人邮件服务器地址
    username: 3178501151@qq.com # 配置用户的账号
    password: waksjtsfilsidcea # 配置用户的密码（即上面我们申请到的授权码）
    default-encoding: UTF-8 #邮件登录字符集编码
    transport:
      protocol: smtp
    smtp:
      auth: true
      ssl:
        enable: true
        socketFactory: javax.net.ssl.SSLSocketFactory # SSL 连接配置
    properties:
      mail:
        debug: true
#设置默认密码
default_password: 123456


